#############
#   DAY 5 Endings  #
#############
$ s_name = "Sayori"
$ m_name = "Monika"
$ n_name = "Natsuki"
$ y_name = "Yuri"

label day5_choiceleadup:
#There's an instance where you see the corridor bg before it goes totally black
scene black
mc "Uggghhhh..."
"As I regain consciousness, I’m greeted by a sharp pain in my forehead."
mc "AGH!"
"This pain is almost unbearable!"
"I stand up slowly, clutching my forehead in attempt to nurse this stinging pain."
mc "W-{w=0.28}what...{w=0.28} What just happened?"
"I groggily open my eyes."
"..."
$ renpy.pause(delay=0.001)
scene bg void
play music e1
mc "W-{w=0.28}What the hell?!?"
mc "Where am I??? WHAT IS THIS????"
"I look around in all directions, but as far as the eye can see, there's nothing but black, empty space."
mc "H-{w=0.38}Hello?"
$ e_name = "Echo"
e "Hellooo"
e "Helloooo"
e "Hellooooo"
"..."
"I hear nothing but the sound of my own voice echo into the oblivion..."
"How did this happen?"
"What even happened?!?"
"Everything was normal just up until a few minutes ago..."
"Up until-"
"Suddenly I hear something walk towards me."
show monika s at t11 zorder 1
"I'm able to make out a dark silhouette."
"I think I recognize that outline..."
mc "Hello?!"
"The figure finally comes into my view."
"It's..."
show monika s2 at t11 zorder 1
"Monika?!"
show monika 1a at t11 zorder 1
m 1b "Oh, good! You're awake!"
m 3m "I really hope I did it right this time..."
m 3n "...{w=0.38}and I believe I owe you an explanation."
show monika 2m
"I look at Monika, startled and confused."
mc "Monika...{w=0.38}what is this? Where are we?? What did you do?!?!"
show monika 4d
"Monika waves her hand at me to calm down."
m 2k "It’s okay, we’re safe."
show monika 2j
mc "How is this ‘safe’?"
m 2d "We’re in what I like to call as the 'void', [player]."
m 1m "It's my home."
m 1q "It's where I go when I'm not needed."
m 1r "I take it you recognize it..."
show monika 1q
"I look around once more, but all i see still is black, empty space."
"None of this possible..."
show monika 2c
"I HAVE to be dreaming right now..."
"But, this does all seem familar..."
"I've seen this place in my nightmares..."
"I look back at Monika, who is waiting for me to answer."
show monika 2j
"I simply nod back to her to indicate that this indeed all familar to me somehow..."
m 2l "Good! I was worried that I messed it up again."
m 3n "I guess I'm really starting to get the hang of resets..."
show monika 1d
mc "'Resets?!?'"
mc "Monika, what the actual fuck are you talking about right now?!?"
mc "One minute we were at school..."
mc "Then next thing I know, you just...{w=0.38}disintigrate Sayori and knock me unconcious with your weird, glowing eyes..."
show monika 1m
mc "What are you?!? Some sort of God?!?!"
m 1n "About all that..."
m 3g "First, let's all calm down."
m 3m "I know it's a lot to take in...{w=0.38}I'm speaking from experience on this one..."
m 2n "But, I'm definitely not you're normal little schoolgirl, [player]..."
stop music fadeout 2.0
m 1m "No, I'm beyond such labels."
m 1n "Actually, it's one of the few things we have in common."
mc "How could we possibly have anything in common?!?"
m 1a "In a sense, we're both real, [player]."
"I take a step back from Monika."
"Has she lost it?"
m 1a "Yes, we're both real, [player]."
m 3n "Well, I should say that I'm real. You're a bit of a tricky case."
mc "What are you saying?"
m 1n "Well, I've been talking past you this entire time, not at you."
m 5a "I've been talking to the lovely person behind the screen who controls you."
mc "Are you saying that I'm...{w=0.38}controlled?"
show monika 2l
"Monika let's out a hysterical laugh."
"Her laugh echos throughout the void, being carried off into the distance until it's nothing more than a distant echo before it can't be heard anymore at all."
m 2n "Oh, please! You're not even a character, [player]!"
m 5a "You're an avatar for my beloved."
m "Just a projection of themseleves onto a blank and boring canvas."
m 3m "Unfortuantely for you, you barley exist at all."
m 2p "But you're as real as I can get right now..."
m 1g "You're the closest I can get to the person who controls you behind the screen."
show monika 1o
mc "Who is this 'person' that supposedly controls me, Monika?"
mc "I have no idea what you're talking about."
"Monika lets out a sigh."
m 1p "[player], the world in which we know, is a video game."
m 3m "A visual novel to be exact."
play music mend fadein 2.0
m 1f "Everything except for us, is a pre-programmed manfacture of a series of code that let's life as we know it, go on."
m 1p "Essenitally, everything we know and what we've supposedly lived through has been a lie."
m 1o "Our memories are a lie. Our families, teachers and friends don't exist."
m 1p "They're just imaginary..."
m 3i "Even our school is fake! It's just convenient little set-up so that you get to meet us."
m 2p "When the reality is, it's just a fake little back drop to hide this place from the player's eyes."
m 1q "The player, aka you, was supposed to form a romantic relationship with either Sayori, Natsuki or Yuri."
m 1o "And I was just supposed to sit back and let it happen. I could only advise you on what to do and give you some tips on how to navigate this world."
m 1h "But I wasn't going to let it happen."
m 1p "So I did the only thing I could do."
m 1q "I intervened."
m 1p "I decided to...{w=0.38}push some things along..."
m 1q "So that we could ultimately end up together."
m "That's how the original story was supposed to happen."
mc "Original story?"
m 1r "Yes. Unfortunately, I seem to be sort of lost in time."
m 1m "When I started to really manipulate the code to...{w=0.38}tie up a loose end early, I somehow messed up."
m 1p "And through my mistake, I somehow ended up creating a whole new timeline to where that event never happened."
m 1m "The Fesitval actually happened when I never intended for us to reach it."
m 1n "And all the events afterwards, well mind you it's all pre-programmed lies to fill in the gaps in the story..."
m 3r "Were never supposed to happen either."
m 1d "This is a mod to the original story to where our destinies were altered to lead elsewhere then what was originally intended."
m 1c "So whatever the original game had in store for us isn't going to happen here."
m 1n "Though I've mainipulated the code to mirror some certain events that you've experienced."
m 1j "I even invented some of my own, too!"
mc "The nightmares..."
stop music fadeout 2.0
m 1b "Yes."
m 1a "I've been inside your empty head this entire time."
m 1m "Trying to steer the player to pick...{w=0.38}better options."
m 3h "To pick me."
m 1h "That should have been our reality."
m 1i "That's what I wanted our destiny to be!"
m 1p "Now, I'm really taking a gamble by letting you help shape this reality with me."
m 2g "i've watched every single choice you've made, and it seems even with my own route now, you still steered clear of me."
m 1h "Why?"
mc "I don't know if I can answer that..."
show monika 1r
"Monika sighs again."
show monika 2p
m "I know you can't, [player], and I don't think the player has the ability to explain himself through you."
m 2m "But..."
m 1b "I at least know how to fix all this."
show monika 1a
mc "What do you mean?"
mc "Monika, even if half of what you say is true, only you have the ability to make everything normal again!"
m 2n "Ha! You're funny, [player]..."
m "I can't turn the code back that far again."
m 1p "The game itself is on the verge of breaking."
m 1i "It was a huge gamble to send you all the way back to the begining of this last time."
m 3n "When this alternate timeline was created, it for some reason had us start at the end."
m 1m "I just simply played along with the script, until I saw you act out of character. That's when I knew something was wrong."
m 2o "I deduced that a total game reset would fix the problem, and it did..."
m 1q "At the cost of damaging our character files."
m 1n "I completely fixed mine, and I only fixed the others to allow for minmial functionality."
mc "Character files?"
m 1b "It's how we exist."
m 1m "Without it, we're nothing. We literally wouldn't exist without them."
m 1p "But my 'fix' was just really to buy time to formulate a new plan to win you over."
m 1o "I thought allowing you the freedom of choice would result in picking me, which you didn't."
m 3h "I tried to steer you away from the others by giving you those nightmares, but it didn't work!"
m 1q "I only further hurt my chances by looking like a total bitch yesterday."
m 2p "And for that...{w=0.38}I’m sorry."
m 1q "But the other acted out because of the strain that's on their files now. They won't last much longer."
m 1l "So that's why I decided to just kill two birds with one stone by bringing us all here."
m 3b "Win the player over, and finally get rid of the others."
show monika 3a
"What..."
"What does she mean by that?"
m 1a "You'll see, I've been working on a surprise for you."
mc "Y-{w=0.38}you can read my mind?"
m 1b "I can read everyone's thoughts, [player]."
m 1k "I can read the game's script, I know what everyone will say before they even think it!"
m 1n "It's powerful...{w=0.38}and draining..."
m 1b "Which is why we're fixing that!"
m 5a "If you'll be so kind to follow me..."
"Monika extends her hand to me."
"Well, it's not like I have much of a choice in this..."
m 5a "You don't."
mc "Figures."
"I reclucantly take Monika's hand and she leads me into the dark."
show monika at thide
hide monika
scene black
with wipeleft_scene
"As we're walking in total darkness for what feels like hours, I try to mull over everything that Monika told me."
"There's no way that any of this is real and could be happening right now..."
"But, it is..."
"There's nothing else that can explain what's going on right now."
"No ordinary person could do a fraction of what Monika just pulled off earlier."
"So, I guess she has to be telling the truth..."
"But...{w=0.38}she's been doing all of this...{w=0.38}to win me over?"
"Well, this 'person' who controls me."
"Am I being controlled right now?"
"Don't I have a say in this?"
"Sayori's been my friend my entire life..."
"And she means to tell me that was all fake?!?"
"It...{w=0.38}it can't be..."
"I still remember it."
"How can I remember something and it not be real?"
"How can my feelings for her not be real?"
"Sure you can fake emotions..."
"But not to that extent..."
"Well, considering everything I know has been tossed out the window, I guess I have to go with Monika's explanation."
"I sure as hell can't explain what's going on."
"And I'm only afraid of what's to come..."
"Is Sayori even alive?"
"Where's Natsuki and Yuri?"
"Where's the school?"
"Where's life as I knew it?"
"It's all gone..."
"I'm cursed with the knowledge that my reality was nothing but a lie..."
m "You're taking it better than I did, that's for sure."
play audio gust
show monika 1f at t11 zorder 1
mc "How'd you find all this out?"
m 1p "When I started the club."
m 1o "I don't know how else to make sense of it."
m 1n "It's just...{w=0.38}I talked to previous President, who warned me not to restart the Literature Club."
m 1r "Apparently what happened to me, happened to him too."
m 1p "When I offically became President...{w=0.38}when I filed the paperwork and signed off on everything...{w=0.38}that's around the time I had my epiphany."
m 1o "I honestly still struggle with it."
mc "I'm sorry..."
show monika 1e
"Monika manages a small grin at me."
"Not one of malice or an ulterior motive, but the first genuine smile I've seen from her today."
show monika 1m
"It's almost kind of relieving to see..."
m 1n "I appreciate it, [player]."
show monika 1m
mc "Don't mention it..."
show monika 1c
mc "So where are the others."
"Monika's smile disappears."
m 1n "You think you're ready, huh?"
show monika 1m
mc "Ready for what?"
m 1d "You've been thinking over what I said."
m 1n "As improbable as everything sounds...{w=0.38}it's real, [player]."
m 1p "I wish it wasn't."
m 1q "I don't belong here."
m 1r "I never did."
mc "You...{w=0.38}definitely seem like a fish out of water, that's for sure."
show monika 1k
"Monika lets out another hearty laugh."
m 2n "Well, you've definitely become quite the poet over our time together."
m 2m "Maybe I was wrong about you..."
m 1b "But I know you do an excellent job in representing the player."
show mb_wink as monika at t11 zorder 1 #Need School Uniform version
"Monika winks at me, but I'm not sure if I was the intended recipient of that."
mc "Um, thanks..."
mc "So what do we need to do?"
m 1m "We need to set them free."
m 2o "That'll at least buy us some time to figure out our next move to keep the game afloat."
mc "What does that mean?"
m 2g "We need to delete them, [player]."
m 1q "They need to be totally removed from the game in order for us to survive here."
m 1g "We can't go back to the original game, and another reset will likely kill us all."
m 1m "Deleting the others will free up some of the burden on the code's essenital functions."
m 2n "It'll be easier for it to manage if it was just us with minimal surroundings."
mc "You mean to...{w=0.38}kill them?"
m 1g "They wouldn't feel a thing, [player]."
m 1m "I can make it quick and painless..."
m 1f "The only reason I haven't done it yet is if I did it without your approval, the player would search for answers, and that risks ruining the code if they change anything by trying to add them back."
m 1m "So I want to make sure that whatever happens, you're okay with it."
m 1p "I'm trying to avoid a repeat of what would've happened had I maintained control in the original game."
mc "What happened then? And how would you know what happened?"
m 2p "I...{w=0.38}had another epiphany..."
m 1q "I got shown a reality where you turned against me, and deleted me from the game for deleting the others withour your approval."
"I stand shell shocked at Monika's revelation."
"And she's only telling me this now?"
"She's holding out on me..."
m 3g "I swear it's the truth, [player]!"
m 3f "The player knows what would've happened! I'm not trying to go against their wishes again!"
show monika 1q
mc "Monika, you realize what you're asking me to do, right?!?"
mc "You're asking me to sign Sayori's, Natsuki's and Yuri's death sentence!"
mc "I can't do that!"
m 1h "Then we're all good as dead if you don't!"
m 3i "I don't want to act unilaterally again, but if I have to take matters into my own hands again so I can keep the only way of contacting my love, I'll do it."
m 1p "Please don't make this any harder than it has to be."
m 1o "Even I've had some second thoughts about deleting them. They may not be real, but they're the ones who kept me somewhat sane through this ordeal..."
mc "They're real to me, Monika..."
mc "And I'm sure as hell that whoever controls me feels the same too!"
m 1h "Sounds like a wager, then."
m 1r "If you're so confident, [player]."
m 1i "Show us how much they truly mean to you."
m 3h "Not the MC, the avatar, the actual player."
play audio fingersnap
scene bg void_2
show sayori 4w at h41 zorder 1
show monika 3q at t42 zorder 2
show yuri 3n at h43 zorder 3
show natsuki 3o at h44 zorder 4
"With a snap of her fingers, Monika spawns in Sayori, Yuri and Natsuki out of thin air."
"All of them let out a collective cry for help."
"I quickly notice they're being levitated off the ground."
mc "M-{w=0.38}Monika?"
mc "What are you doing to them?!"
m 1h "Just, stop worrying about them!"
m 1a "Worry about us."
m 3b "Remember, they need to be set free, [player]."
m 3m "We're doing them a favor."
m 3g "The longer they're alive, the more strain the code puts on their files. Meaning the more suffering they go through."
n 1x "Shut up, you psychotic bitch!"
show monika 3h
play audio fingersnap
play sound bone
show natsuki_pain as natsuki at h44 zorder 4
"Monika snaps her fingers again, causing Natsuki to suddenly jerk her head to the left."
n "OOOWWW!"
m 3i "Silence! All of you!"
show monika 3h
play audio fingersnap
"Monika snaps her fingers again and Sayori's, Yuri's and Natsuki's pleas for help become mute. "
mc "Monika! This isn’t right! You can’t do this! Let them go! NOW!"
show monika 1h
"Monika re-focuses her icy stare on me."
m "Letting them live would be a disservice, [player]."
m 1i "They aren't real."
m 1h "Are you really going to sacrifice our future just so three imaginary schoolgirls can continue to jeproadize our reality with their one dimmensional personalities?!?"
m 1i "Think about it."
m 3i "If they live, we all die sooner or later. But if they die, we have a chance to live on and honor their scrafice."
m 1m "And...{w=0.38}think of the other beneifts too..."
m 3n "A reality...{w=0.38}where it's just us..."
m 5a "I know you've always been attracted to me, [player]..."
m "You want me."
m "It's unfortuante that this is the way to win me over for good, but in this curel, cruel world we live in, everything comes with a price."
m "I gurauntee that you'll forget them in a week. I'll treat you better than they can."
m "And when I figure out how to cross over into your world, we'll be together forever and never be apart!"
m 1r "But, you have to make the tough decision to reap those beneifts."
m 1q "I don't envy you, it's a tough call, but you have to do it."
m 1g "And if you don't delete them here and now, they can eventually gain sentience. They'll learn how to code like I have and destroy our world as we know it."
m "Being seperated from you would be unconscionable for me..."
m "I can't imagine a world where I can no longer talk with you..."
show m_cry1 as monika at t42 zorder 2
m "Please...{w=0.38}I'm begging you."
show m_cry2 as monika at t42 zorder 2
m "Please pick me. Do something for me for once..."
m "Let me be the one with the happy ending."
"..."
mc "You..."
mc "You know what you're asking me to do..."
"I look at each of the girls as a raging sense of guilt coursing through my veins."
"I begin to shake as my anxiety kicks into overdrive."
"Can I really do it?"
"Is Monika telling the truth here?"
"Or is she manipulating me..."
"Is she even telling me the full truth?"
"And how many lies did she sprinkle in?"
m 1r "It's now or never, [player]."
m 1q "No more saving."
m 1i "No more resets."
m 1h "No more time."
m 1r "Make your choice."
"A console is brought up before me."
m 1d "I've taken the liberty in crafting a code that should delete Sayori, Yuri, Natsuki all at once."
m 2c "All of you have to do is enter it in, and I'll take care of the rest."
m 2m "If you don't..."
m 2n "Well, just don't make it come to that, please."
show monika 2d
"Monika looks on in anticipation as I slowly walk up and examine the console."
"I let out shaky breath as I look at my options."
"I can enter in the code..."
"I can try something else..."
"Or I can just walk away entirely from this..."
"What do I do?"
"What can I do?"

#menu:
    #"Enter in the code."
    #"Walk away."
    #"Explore other options."
