########################################################################
# This file was created automatically by the Dynamic Pose Tool v1.4.   #
# You may edit this file manually, but be aware it will be overwritten #
# without confirmation the next time the tool is run and your changes  #
# will be lost.                                                        #
#                                                                      #
# It is recommended to only make temporary changes for test purposes   #
# which are harmless to lose in an overwrite.                          #
########################################################################

# MONIKA
image monika l1111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_lean/1_body/base.png", (0, 0), "mod_assets/character_images/monika/3_alt_face/base.png", (0, 0), "mod_assets/character_images/monika/3_alt_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/3_alt_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/3_alt_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/3_alt_face/4_eyebrows/1.png")
image monika u111111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u111131 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/3.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u111151 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/5.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u111311 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u111331 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/3.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u111394 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/9.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/4.png")
image monika u112332 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/2.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/3.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/2.png")
image monika u113113 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/3.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/3.png")
image monika u113342 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/3.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/4.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/2.png")
image monika u114111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u114211 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/2.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u114311 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u114312 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/2.png")
image monika u114341 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/4.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u11h113 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/h.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/3.png")
image monika u121111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u121112 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/2.png")
image monika u121331 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/3.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u121351 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/3.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/5.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u123111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/1.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/3.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u212131 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/2.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/3.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u212232 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/2.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/2.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/3.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/2.png")
image monika u214111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u214113 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/1.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/3.png")
image monika u221111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/1.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u222111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/2.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u224111 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/1.png")
image monika u224112 = im.Composite((960, 960), (0, 0), "mod_assets/character_images/monika/1_uniform/1_body_left/2.png", (0, 0), "mod_assets/character_images/monika/1_uniform/2_body_right/2.png", (0, 0), "mod_assets/character_images/monika/2_face/base.png", (0, 0), "mod_assets/character_images/monika/2_face/1_mouth/4.png", (0, 0), "mod_assets/character_images/monika/2_face/2_nose/1.png", (0, 0), "mod_assets/character_images/monika/2_face/3_eyes/1.png", (0, 0), "mod_assets/character_images/monika/2_face/4_eyebrows/2.png")



